### ISSUE TITLE
About /data/WMPC_CNN_0_0_softmax.pickle and /data/WMPC_MFE_0_0_softmax.pickle

### ISSUE THREAD

**Issue by sumhncku** [DMkelllog/WMPC_Stacking_TF2#1]
Since I did not find the information of these two files,WMPC_CNN_0_0_softmax.pickle and WMPC_MFE_0_0_softmax.pickle, 
I would like to ask how to generate these two files?
Thanks

**Comment by DMkelllog** [comment]
Hi, I forgot to add additional execution files for preliminaries. You first need to execute run files from [WMPC_CNN_TF2](https://github.com/DMkelllog/WMPC_CNN_TF2) and [WMPC_MFE_TF2](https://github.com/DMkelllog/WMPC_MFE_TF2). Then, the prediction files will be created. Thanks
